apiVersion: v1
kind: Service
metadata:
  name: rag-doc-intelligence
spec:
  selector:
    app: rag-doc-intelligence
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
